# Query Design for BQ-2

SELECT RANK, [Product Code] As [Product Number],[Gross Margin] FROM ((SELECT PRODUCT_DIM.["UPC_Number"] AS [Product Code], SUM(PRODUCT_SALES_FACT.Sales) AS [Gross Margin], RANK() OVER
(ORDER BY SUM(PRODUCT_SALES_FACT.Sales) DESC) AS Rank
FROM PRODUCT_DIM INNER JOIN
PRODUCT_SALES_FACT ON PRODUCT_DIM.["Product_ID"] = PRODUCT_SALES_FACT.Product_ID INNER JOIN
STORE_DIM ON PRODUCT_SALES_FACT.Store_ID = STORE_DIM.Store_ID INNER JOIN
TIME_DIM ON PRODUCT_SALES_FACT.Time_ID = TIME_DIM.Time_ID
WHERE (PRODUCT_DIM.["Product_Type"] = N'Canned Soup') AND (STORE_DIM.Price_Tier = N'Medium') AND (TIME_DIM.Year = 1990)
GROUP BY PRODUCT_DIM.["UPC_Number"])) TABLE1
WHERE RANK <=10
order by 1 ASC;