RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterIdentifier:
        Fn::Sub: ${ProjectNameLowerCase}-${Environment}-${RedshiftClusterNameSuffix}
      ClusterType:
        Ref: ClusterType
      NumberOfNodes:
        Fn::If:
        - IsSingleNode
        - Ref: AWS::NoValue
        - Ref: RedshiftNodeCount
      NodeType:
        Ref: NodeType
      DBName:
        Fn::Sub: ${DatabaseName}
      MasterUsername:
        Fn::Sub: '{{resolve:secretsmanager:${RedshiftMasterUserSecret}::username}}'
      MasterUserPassword:
        Fn::Sub: '{{resolve:secretsmanager:${RedshiftMasterUserSecret}::password}}'
      ClusterParameterGroupName:
        Ref: RedshiftClusterParameterGroup
      VpcSecurityGroupIds:
      - Fn::Sub: ${RedshiftSecurityGroup}
      ClusterSubnetGroupName:
        Ref: RedshiftClusterSubnetGroup
      PubliclyAccessible: false
      Encrypted: true
      Port: 5439
      IamRoles:
      - Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${ProjectNameShort}${EnvNameCamelCase}RedshiftLoadRole
        - EnvNameCamelCase:
            Fn::FindInMap:
            - EnvironmentMap
            - Ref: Environment
            - CamelCase
      - Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${ProjectNameShort}${EnvNameCamelCase}RedshiftUnloadRole
        - EnvNameCamelCase:
            Fn::FindInMap:
            - EnvironmentMap
            - Ref: Environment
            - CamelCase
      PreferredMaintenanceWindow:
        Fn::Sub: ${MaintenanceWindow}