# CATEGORYSALES_FACT

CREATE TABLE [dbo].[CategorySales_FACT](
[CATEGORYSALES_ID] [int] NOT NULL PRIMARY KEY,
[Store_ID] [int] NOT NULL FOREIGN KEY REFERENCES [STORE_DIM]([Store_ID]),
[Time_ID] [int]NOT NULL FOREIGN KEY REFERENCES [TIME_DIM]([Time_ID]),
[Category_ID] [numeric](18, 0) NOT NULL FOREIGN KEY REFERENCES [CATEGORY_DIM]([Category_ID]),
[Sales] [numeric](18, 4) NULL
);